INSERT INTO libre_user (id, avatar, name)
VALUES (NULL, '/assets/images/avatars/buffdude-1.png', 'Arnie');

INSERT INTO food_category (shortvalue, longvalue)
VALUES ('b', 'Breakfast'),
       ('l', 'Lunch'),
       ('d', 'Dinner'),
       ('s', 'Snack'),
       ('t', 'Treat'),
       ('u', 'Unset');


INSERT INTO weight_tracker (id, added, amount)
VALUES ( DATE('now', '-58 days'), 100.0),
       ( DATE('now', '-57 days'), 100.0),
       ( DATE('now', '-56 days'), 100.0),
       ( DATE('now', '-55 days'), 100.0),
       ( DATE('now', '-54 days'), 100.0),
       ( DATE('now', '-53 days'), 100.0),
       ( DATE('now', '-52 days'), 100.0),
       ( DATE('now', '-51 days'), 100.0),
       ( DATE('now', '-50 days'), 99.0),
       ( DATE('now', '-49 days'), 99.0),
       ( DATE('now', '-48 days'), 99.0),
       ( DATE('now', '-47 days'), 99.0),
       ( DATE('now', '-46 days'), 99.0),
       ( DATE('now', '-45 days'), 98.0),
       ( DATE('now', '-44 days'), 98.0),
       ( DATE('now', '-43 days'), 98.0),
       ( DATE('now', '-42 days'), 98.0),
       ( DATE('now', '-41 days'), 97.0),
       ( DATE('now', '-40 days'), 97.0),
       ( DATE('now', '-39 days'), 97.0),
       ( DATE('now', '-38 days'), 97.0),
       ( DATE('now', '-37 days'), 97.0),
       ( DATE('now', '-36 days'), 97.0),
       ( DATE('now', '-35 days'), 97.0),
       ( DATE('now', '-34 days'), 97.0),
       ( DATE('now', '-33 days'), 97.0),
       ( DATE('now', '-32 days'), 97.0),
       ( DATE('now', '-31 days'), 97.0),
       ( DATE('now', '-30 days'), 97.0);

INSERT INTO calorie_tracker (id, added, amount, category, description)
VALUES ( DATE('now', '-58 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-58 days'), 270, 'l', 'Lunch'),
       ( DATE('now', '-58 days'), 900, 'd', 'Dinner'),
       ( DATE('now', '-58 days'), 518, 's', 'Snack'),
       ( DATE('now', '-57 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-57 days'), 650, 'l', 'Lunch'),
       ( DATE('now', '-57 days'), 500, 'd', 'Dinner'),
       ( DATE('now', '-57 days'), 600, 's', 'Snack'),
       ( DATE('now', '-56 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-56 days'), 650, 'l', 'Lunch'),
       ( DATE('now', '-56 days'), 450, 'd', 'Dinner'),
       ( DATE('now', '-56 days'), 240, 's', 'Snack'),
       ( DATE('now', '-55 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-55 days'), 900, 'l', 'Lunch'),
       ( DATE('now', '-55 days'), 577, 'd', 'Dinner'),
       ( DATE('now', '-55 days'), 450, 's', 'Snack'),
       ( DATE('now', '-54 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-54 days'), 950, 'l', 'Lunch'),
       ( DATE('now', '-54 days'), 535, 'd', 'Dinner'),
       ( DATE('now', '-54 days'), 142, 's', 'Snack'),
       ( DATE('now', '-53 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-53 days'), 375, 'l', 'Lunch'),
       ( DATE('now', '-53 days'), 1000, 'd', 'Dinner'),
       ( DATE('now', '-53 days'), 320, 's', 'Snack'),
       ( DATE('now', '-52 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-52 days'), 450, 'l', 'Lunch'),
       ( DATE('now', '-52 days'), 1400, 'd', 'Dinner'),
       ( DATE('now', '-52 days'), 160, 's', 'Snack'),
       ( DATE('now', '-51 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-51 days'), 450, 'l', 'Lunch'),
       ( DATE('now', '-51 days'), 650, 'd', 'Dinner'),
       ( DATE('now', '-51 days'), 890, 's', 'Snack'),
       ( DATE('now', '-50 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-50 days'), 900, 'l', 'Lunch'),
       ( DATE('now', '-50 days'), 550, 'd', 'Dinner'),
       ( DATE('now', '-50 days'), 160, 's', 'Snack'),
       ( DATE('now', '-49 days'), 600, 'b', 'Breakfast'),
       ( DATE('now', '-49 days'), 810, 'l', 'Lunch'),
       ( DATE('now', '-49 days'), 346, 'd', 'Dinner'),
       ( DATE('now', '-49 days'), 160, 's', 'Snack'),
       ( DATE('now', '-48 days'), 160, 'b', 'Breakfast'),
       ( DATE('now', '-48 days'), 800, 'l', 'Lunch'),
       ( DATE('now', '-48 days'), 850, 'd', 'Dinner'),
       ( DATE('now', '-48 days'), 400, 's', 'Snack'),
       ( DATE('now', '-47 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-47 days'), 950, 'l', 'Lunch'),
       ( DATE('now', '-47 days'), 600, 'd', 'Dinner'),
       ( DATE('now', '-47 days'), 160, 's', 'Snack'),
       ( DATE('now', '-46 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-46 days'), 750, 'l', 'Lunch'),
       ( DATE('now', '-46 days'), 627, 'd', 'Dinner'),
       ( DATE('now', '-46 days'), 160, 's', 'Snack'),
       ( DATE('now', '-45 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-45 days'), 560, 'l', 'Lunch'),
       ( DATE('now', '-45 days'), 600, 'd', 'Dinner'),
       ( DATE('now', '-45 days'), 640, 's', 'Snack'),
       ( DATE('now', '-44 days'), 480, 'b', 'Breakfast'),
       ( DATE('now', '-44 days'), 560, 'l', 'Lunch'),
       ( DATE('now', '-44 days'), 750, 'd', 'Dinner'),
       ( DATE('now', '-44 days'), 160, 's', 'Snack'),
       ( DATE('now', '-43 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-43 days'), 800, 'l', 'Lunch'),
       ( DATE('now', '-43 days'), 800, 'd', 'Dinner'),
       ( DATE('now', '-43 days'), 139, 's', 'Snack'),
       ( DATE('now', '-42 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-42 days'), 950, 'l', 'Lunch'),
       ( DATE('now', '-42 days'), 605, 'd', 'Dinner'),
       ( DATE('now', '-42 days'), 160, 's', 'Snack'),
       ( DATE('now', '-41 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-41 days'), 800, 'l', 'Lunch'),
       ( DATE('now', '-41 days'), 700, 'd', 'Dinner'),
       ( DATE('now', '-41 days'), 600, 's', 'Snack'),
       ( DATE('now', '-40 days'), 376, 'b', 'Breakfast'),
       ( DATE('now', '-40 days'), 240, 'l', 'Lunch'),
       ( DATE('now', '-40 days'), 800, 'd', 'Dinner'),
       ( DATE('now', '-40 days'), 600, 's', 'Snack'),
       ( DATE('now', '-39 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-39 days'), 600, 'l', 'Lunch'),
       ( DATE('now', '-39 days'), 810, 'd', 'Dinner'),
       ( DATE('now', '-39 days'), 160, 's', 'Snack'),
       ( DATE('now', '-38 days'), 800, 'b', 'Breakfast'),
       ( DATE('now', '-38 days'), 240, 'l', 'Lunch'),
       ( DATE('now', '-38 days'), 750, 'd', 'Dinner'),
       ( DATE('now', '-38 days'), 900, 's', 'Snack'),
       ( DATE('now', '-37 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-37 days'), 650, 'l', 'Lunch'),
       ( DATE('now', '-37 days'), 730, 'd', 'Dinner'),
       ( DATE('now', '-37 days'), 160, 's', 'Snack'),
       ( DATE('now', '-36 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-36 days'), 1000, 'l', 'Lunch'),
       ( DATE('now', '-36 days'), 600, 'd', 'Dinner'),
       ( DATE('now', '-36 days'), 285, 's', 'Snack'),
       ( DATE('now', '-35 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-35 days'), 450, 'l', 'Lunch'),
       ( DATE('now', '-35 days'), 1200, 'd', 'Dinner'),
       ( DATE('now', '-35 days'), 760, 's', 'Snack'),
       ( DATE('now', '-34 days'), 450, 'b', 'Breakfast'),
       ( DATE('now', '-34 days'), 240, 'l', 'Lunch'),
       ( DATE('now', '-34 days'), 650, 'd', 'Dinner'),
       ( DATE('now', '-34 days'), 700, 's', 'Snack'),
       ( DATE('now', '-33 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-33 days'), 400, 'l', 'Lunch'),
       ( DATE('now', '-33 days'), 750, 'd', 'Dinner'),
       ( DATE('now', '-33 days'), 369, 's', 'Snack'),
       ( DATE('now', '-32 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-32 days'), 700, 'l', 'Lunch'),
       ( DATE('now', '-32 days'), 840, 'd', 'Dinner'),
       ( DATE('now', '-32 days'), 160, 's', 'Snack'),
       ( DATE('now', '-31 days'), 240, 'b', 'Breakfast'),
       ( DATE('now', '-31 days'), 650, 'l', 'Lunch'),
       ( DATE('now', '-31 days'), 660, 'd', 'Dinner'),
       ( DATE('now', '-31 days'), 400, 's', 'Snack');

INSERT INTO calorie_tracker (id, added, amount, category, description)
VALUES (NULL, DATE('now', '-30 day'), 0, 'b', 'Breakfast'),
       (NULL, DATE('now', '-30 day'), 650, 'l', 'Lunch'),
       (NULL, DATE('now', '-30 day'), 1200, 'd', 'Dinner'),
       (NULL, DATE('now', '-29 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-29 day'), 450, 'l', 'Lunch'),
       (NULL, DATE('now', '-29 day'), 1000, 'd', 'Dinner'),
       (NULL, DATE('now', '-29 day'), 180, 's', 'Snack'),
       (NULL, DATE('now', '-28 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-28 day'), 750, 'l', 'Lunch'),
       (NULL, DATE('now', '-28 day'), 1200, 'd', 'Dinner'),
       (NULL, DATE('now', '-27 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-27 day'), 1200, 'l', 'Lunch'),
       (NULL, DATE('now', '-27 day'), 800, 'd', 'Dinner'),
       (NULL, DATE('now', '-26 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-26 day'), 700, 'l', 'Lunch'),
       (NULL, DATE('now', '-26 day'), 700, 'd', 'Dinner'),
       (NULL, DATE('now', '-25 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-25 day'), 1000, 'l', 'Lunch'),
       (NULL, DATE('now', '-25 day'), 643, 'd', 'Dinner'),
       (NULL, DATE('now', '-25 day'), 139, 's', 'Snack'),
       (NULL, DATE('now', '-24 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-24 day'), 643, 'l', 'Lunch'),
       (NULL, DATE('now', '-24 day'), 820, 'd', 'Dinner'),
       (NULL, DATE('now', '-24 day'), 139, 's', 'Snack'),
       (NULL, DATE('now', '-23 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-23 day'), 1250, 'l', 'Lunch'),
       (NULL, DATE('now', '-23 day'), 350, 'd', 'Dinner'),
       (NULL, DATE('now', '-22 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-22 day'), 750, 'l', 'Lunch'),
       (NULL, DATE('now', '-22 day'), 750, 'd', 'Dinner'),
       (NULL, DATE('now', '-22 day'), 400, 's', 'Snack'),
       (NULL, DATE('now', '-21 day'), 300, 'b', 'Breakfast'),
       (NULL, DATE('now', '-21 day'), 750, 'l', 'Lunch'),
       (NULL, DATE('now', '-21 day'), 900, 'd', 'Dinner'),
       (NULL, DATE('now', '-20 day'), 440, 'b', 'Breakfast'),
       (NULL, DATE('now', '-20 day'), 650, 'l', 'Lunch'),
       (NULL, DATE('now', '-20 day'), 900, 'd', 'Dinner'),
       (NULL, DATE('now', '-20 day'), 359, 's', 'Snack'),
       (NULL, DATE('now', '-19 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-19 day'), 850, 'l', 'Lunch'),
       (NULL, DATE('now', '-19 day'), 300, 'd', 'Dinner'),
       (NULL, DATE('now', '-19 day'), 400, 's', 'Snack'),
       (NULL, DATE('now', '-18 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-18 day'), 850, 'l', 'Lunch'),
       (NULL, DATE('now', '-18 day'), 565, 'd', 'Dinner'),
       (NULL, DATE('now', '-18 day'), 300, 's', 'Snack'),
       (NULL, DATE('now', '-17 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-17 day'), 650, 'l', 'Lunch'),
       (NULL, DATE('now', '-17 day'), 800, 'd', 'Dinner'),
       (NULL, DATE('now', '-17 day'), 284, 's', 'Snack'),
       (NULL, DATE('now', '-16 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-16 day'), 700, 'l', 'Lunch'),
       (NULL, DATE('now', '-16 day'), 600, 'd', 'Dinner'),
       (NULL, DATE('now', '-15 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-15 day'), 1200, 'l', 'Lunch'),
       (NULL, DATE('now', '-15 day'), 400, 'd', 'Dinner'),
       (NULL, DATE('now', '-14 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-14 day'), 400, 'l', 'Lunch'),
       (NULL, DATE('now', '-14 day'), 2400, 'd', 'Dinner'),
       (NULL, DATE('now', '-13 day'), 0, 'b', 'Breakfast'),
       (NULL, DATE('now', '-13 day'), 650, 'l', 'Lunch'),
       (NULL, DATE('now', '-13 day'), 800, 'd', 'Dinner'),
       (NULL, DATE('now', '-13 day'), 384, 's', 'Snack'),
       (NULL, DATE('now', '-12 day'), 383, 'b', 'Breakfast'),
       (NULL, DATE('now', '-12 day'), 750, 'l', 'Lunch'),
       (NULL, DATE('now', '-12 day'), 800, 'd', 'Dinner'),
       (NULL, DATE('now', '-11 day'), 0, 'b', 'Breakfast'),
       (NULL, DATE('now', '-11 day'), 950, 'l', 'Lunch'),
       (NULL, DATE('now', '-11 day'), 562, 'd', 'Dinner'),
       (NULL, DATE('now', '-11 day'), 387, 's', 'Snack'),
       (NULL, DATE('now', '-10 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-10 day'), 950, 'l', 'Lunch'),
       (NULL, DATE('now', '-10 day'), 800, 'd', 'Dinner'),
       (NULL, DATE('now', '-10 day'), 500, 's', 'Snack'),
       (NULL, DATE('now', '-9 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-9 day'), 650, 'l', 'Lunch'),
       (NULL, DATE('now', '-9 day'), 1000, 'd', 'Dinner'),
       (NULL, DATE('now', '-8 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-8 day'), 1200, 'l', 'Lunch'),
       (NULL, DATE('now', '-8 day'), 600, 'd', 'Dinner'),
       (NULL, DATE('now', '-7 day'), 0, 'b', 'Breakfast'),
       (NULL, DATE('now', '-7 day'), 950, 'l', 'Lunch'),
       (NULL, DATE('now', '-7 day'), 950, 'd', 'Dinner'),
       (NULL, DATE('now', '-6 day'), 450, 'b', 'Breakfast'),
       (NULL, DATE('now', '-6 day'), 900, 'l', 'Lunch'),
       (NULL, DATE('now', '-6 day'), 900, 'd', 'Dinner'),
       (NULL, DATE('now', '-5 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-5 day'), 1000, 'l', 'Lunch'),
       (NULL, DATE('now', '-5 day'), 650, 'd', 'Dinner'),
       (NULL, DATE('now', '-4 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-4 day'), 950, 'l', 'Lunch'),
       (NULL, DATE('now', '-4 day'), 650, 'd', 'Dinner'),
       (NULL, DATE('now', '-3 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-3 day'), 360, 'l', 'Lunch'),
       (NULL, DATE('now', '-3 day'), 750, 'd', 'Dinner'),
       (NULL, DATE('now', '-3 day'), 700, 's', 'Snack'),
       (NULL, DATE('now', '-2 day'), 240, 'b', 'Breakfast'),
       (NULL, DATE('now', '-2 day'), 650, 'l', 'Lunch'),
       (NULL, DATE('now', '-2 day'), 400, 'd', 'Dinner'),
       (NULL, DATE('now', '-2 day'), 800, 's', 'Snack'),
       (NULL, DATE('now', '-1 day'), 500, 'b', 'Breakfast'),
       (NULL, DATE('now', '-1 day'), 500, 'l', 'Lunch'),
       (NULL, DATE('now', '-1 day'), 900, 'd', 'Dinner'),
       (NULL, DATE('now'), 0, 'b', 'Breakfast'),
       (NULL, DATE('now'), 1000, 'l', 'Lunch'),
       (NULL, DATE('now'), 800, 'd', 'Dinner');

INSERT INTO weight_tracker (id, added, amount)
VALUES (NULL, DATE('now', '-30 day'), 97),
       (NULL, DATE('now', '-29 day'), 97),
       (NULL, DATE('now', '-28 day'), 97),
       (NULL, DATE('now', '-27 day'), 96),
       (NULL, DATE('now', '-26 day'), 96),
       (NULL, DATE('now', '-25 day'), 96),
       (NULL, DATE('now', '-24 day'), 96),
       (NULL, DATE('now', '-23 day'), 96),
       (NULL, DATE('now', '-22 day'), 96),
       (NULL, DATE('now', '-21 day'), 95),
       (NULL, DATE('now', '-20 day'), 95),
       (NULL, DATE('now', '-19 day'), 95),
       (NULL, DATE('now', '-18 day'), 95),
       (NULL, DATE('now', '-17 day'), 95),
       (NULL, DATE('now', '-16 day'), 94),
       (NULL, DATE('now', '-15 day'), 94),
       (NULL, DATE('now', '-14 day'), 94),
       (NULL, DATE('now', '-13 day'), 94),
       (NULL, DATE('now', '-12 day'), 94),
       (NULL, DATE('now', '-11 day'), 94),
       (NULL, DATE('now', '-10 day'), 94),
       (NULL, DATE('now', '-9 day'), 94),
       (NULL, DATE('now', '-8 day'), 94),
       (NULL, DATE('now', '-7 day'), 94),
       (NULL, DATE('now', '-6 day'), 94),
       (NULL, DATE('now', '-5 day'), 94),
       (NULL, DATE('now', '-4 day'), 94),
       (NULL, DATE('now', '-3 day'), 94),
       (NULL, DATE('now', '-2 day'), 93),
       (NULL, DATE('now', '-1 day'), 93),
       (NULL, DATE('now'), 93);

INSERT INTO calorie_target (id, added, start_date, end_date, target_calories, maximum_calories)
VALUES ( DATE('now', '-58 day'), DATE('now', '-58 day'),
        DATE('now', '+307 day'), 1849, 2398);

INSERT INTO weight_target (id, added, start_date, end_date, initial_weight, target_weight)
VALUES ( DATE('now', '-58 day'), DATE('now', '-58 day'),
        DATE('now', '+307 day'), 104, 77);
